# Generated by Django 3.2.25 on 2024-05-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(max_length=254),
        ),
    ]
