# Generated by Django 3.2.25 on 2024-06-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_alter_testimonial_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
