# Generated by Django 3.2.25 on 2024-04-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Untitled', max_length=254),
        ),
    ]
