# Generated by Django 3.2.25 on 2024-04-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sale',
            field=models.BooleanField(default=False),
        ),
    ]
