# Generated by Django 3.2.25 on 2024-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
